// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimpleRDBMSRestfulAPI;

#nullable disable

namespace SimpleRDBMSRestfulAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConnectionInfoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connection_string");

                    b.Property<long>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int8")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("FLOOR(EXTRACT(EPOCH FROM NOW()) * 1000)");

                    b.Property<string>("DbType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("db_type");

                    b.Property<long>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int8")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("FLOOR(EXTRACT(EPOCH FROM NOW()) * 1000)");

                    b.HasKey("Id");

                    b.ToTable("connection_infos");
                });
#pragma warning restore 612, 618
        }
    }
}
